CREATE TABLE WorkAssigned
(
    WorkID INTEGER PRIMARY KEY IDENTITY,
    BookingID INTEGER FOREIGN KEY REFERENCES Booking(BookingID),
    EngineerID INTEGER FOREIGN KEY REFERENCES Engineer(EngineerID),
    StatusID INTEGER FOREIGN KEY REFERENCES WorkStatus(WorkStatusID)
);