INSERT INTO AppointmentSystemDB.dbo.Department
(DepartmentName, DepartmentFloor)
VALUES
('Administration', 17),
('Marketing', 18),
('Purchasing', 17),
('Human Resources', 24),
('Logistic', 15),
('IT', 14),
('Public Relations', 27),
('Sales', 25),
('Executive', 10),
('Finance', 11),
('Accounting', 9),
('Treasury', 9),
('Corporate Tax', 10),
('Control and Credit', 11),
('Shareholder Services', 12),
('Benefits', 16),
('Manufacturing', 13),
('Construction', 13),
('Contracting', 14),
('Operations', 19),
('IT Support', 20),
('NOC', 21),
('IT Helpdesk', 20),
('Government Sales', 21),
('Retail Sales', 22),
('Recruiting', 23),
('Payroll', 17);